Shrikrushna Zirape
41283 (S2)

Problem Statement : 

Classify the email using the binary classification method. Email Spam detection has two states: a) Normal State Not Spam, b) Abnormal State Spam. Use K-Nearest Neighbors and Support Vector Machine for classification. Analyze their performance.
Dataset link: The emails.csv dataset on the Kaggle https://www.kaggle.com/datasets/balaka18/email-spam-classification-dataset-csv


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics

In [4]:
df = pd.read_csv('emails.csv')

In [5]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [6]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [7]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [8]:
df.dropna(inplace=True)

In [10]:
df.drop(['Email No.'], axis=1, inplace=True)

In [13]:
X=df.drop(['Prediction'],axis=1)
y=df['Prediction']

In [14]:
y

0       0
1       0
2       0
3       0
4       0
       ..
5167    0
5168    0
5169    1
5170    1
5171    0
Name: Prediction, Length: 5172, dtype: int64

In [16]:
from sklearn.preprocessing import scale


In [17]:
X = scale(X)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)

### KNN Classifier

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [23]:
y_pred = knn.predict(X_test)

In [25]:
print(y_pred)

[0 0 1 ... 1 1 1]


In [27]:
print("KNN Accuracy : ", metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix : \n", metrics.confusion_matrix(y_test,y_pred))

KNN Accuracy :  0.8009020618556701
Confusion Matrix : 
 [[804 293]
 [ 16 439]]


### SVM Classifier

In [28]:
#Cost c=1
model = SVC(C=1)
#fit
model.fit(X_train,y_train)
#predict
y_pred = model.predict(X_test)

In [30]:
metrics.confusion_matrix(y_true=y_test, y_pred=y_pred)

array([[1091,    6],
       [  90,  365]], dtype=int64)

In [31]:
print("SVM Accuracy : ", metrics.accuracy_score(y_test, y_pred))

SVM Accuracy :  0.9381443298969072
